import turtle
turtle.getscreen()
turtle.title("My Turtle First Program")
turtle.pensize(4)
turtle.forward(200)
turtle.shapesize(3,3,3)
turtle.fillcolor("blue")
turtle.pencolor("yellow")
turtle.color("blue","red")
turtle.forward(100)
turtle.begin_fill()
turtle.fd(100)
turtle.lt(120)
turtle.fd(100)
turtle.lt(120)
turtle.fd(100)
turtle.end_fill()
turtle.shape("turtle")
turtle.shape("arrow")
turtle.shape("circle")
