a,b=input().split()
m,n=input().split()
print(a,n)
print(m,b)
print("---------------")
print(a,n[::-1])
print(m,b[::-1])
print("---------------")
print(m,n[::-1])
print(a,b[::-1])
print("---------------")
print(m[::-1],n[::-1])
print(a[::-1],b[::-1])
print("---------------")
print(n[0]+m[1:]+" "+m[0]+n[1:])
print(b[0]+a[1:]+" "+a[0]+b[1:])

