#count
tuple1=(1,2,3,3,4,4,4,5)
tuple2=tuple1.count(4)
print(tuple2)
#-------------------------------------------------------------
#index
tuple3=(1,2,3,4,5,6,7,8)
tuple4=tuple3.index(4)
print(tuple4)
#-------------------------------------------------------------
#minimum,maximum,sum
tuple5=(1,3,2,4,3,6)
print(min(tuple5))
print(max(tuple5))
print(sum(tuple5))
#--------------------------------------------------------------
tuple6=(1,3,2,4,3,6)
tuple7=tuple6.copy()
print(tuple7)
